### ISSUE TITLE
Update ~ 2016-06-03 ~ New Home Page R2

### ISSUE THREAD

**Issue by theo-armour** [theo-armour/theo-armour.github.io#2]
![image](https://cloud.githubusercontent.com/assets/547626/15796929/33de2f86-29bd-11e6-94d5-f82d0332716d.png)

Peeps want to know what I'm doing.

I want to know what my peeps are doing.

This is an attempt to find a common ground.

The GitHub API has many wonderful features. And GitHub's use of their own AI is really good. Bu are there not other ways of mixing and matching the vast data held by GitHub?

This little effort is an exploration of into responses to that questio.
### 2016-06-03
- R2
- Add hamburger menu
- Select user from drop-down list of user names
- Work on prettifying display of output 
- Add user orgs
- Add user repos

**Comment by paulmasson** [comment]
I was getting ready to open an issue about better indexing for the live versions of things in your repositories when I realized you had made the Github events page your home page. Great idea! In the past when you sent me a link to new work, I had to copy and paste to get to the website version. This is much better for quick access to the latest.

One complaint on format: the hamburger menu is currently over other text, making things look not nice and confusing. Since sliding all of the underlying text is not feasible, how about making the menu itself less transparent?

Also, when going to the next page with the buttons on the bottom, the page should probably scroll to the top to see the next item backwards in time.

Otherwise pretty cool. I may copy this into my own repository in the near future...

**Comment by theo-armour** [comment]
> >  This is much better for quick access to the latest.

Glad you like it

> > One complaint on format: the hamburger menu is currently over other
> > text....

the goal is to have one style sheet that's OK for computer, tablet and
phone. WIP. Very unlikely. If you know of any examples: please shout

> > Also, when going to the next page with the buttons on the bottom, the
> > page should probably scroll to the top to see the next item backwards in
> > time.

Yes, very much an action item,

On the other hand, there's a GitHub limit of 10 pages max. So next
iteration will just try to load the ten - one after the other - on a single
screen...

**Comment by paulmasson** [comment]
@theo-armour I like the opaque menu div. Now just want to see the hamburger div scooched up or down so it's not on the line of text.

**Comment by theo-armour** [comment]
Good idea. Will be adding features to it this evening

**Comment by paulmasson** [comment]
@theo-armour R3 of this page is broken. Can't change active user or see more than first page of activity. 😞

**Comment by theo-armour** [comment]
@paulmasson 

Should be fixed now

**Comment by paulmasson** [comment]
@theo-armour one more feature request: add links to issues and pull requests above the comment events. Makes it easier to get to context of comment.

**Comment by theo-armour** [comment]
@paulmasson 

> > add links to issues and pull requests above the comment events. Makes it easier to get to context of comment.

Was there already - but was failing because of a typo. Working now. Thanks for the heads-up.
